#!/bin/sh

##
# [ ~/.config/bspwm/bspwmrc ]
# Run when bspwm is started.
##

## Monitors, Desktops & Tags
bspc monitor -d 1 2 3

## Window rules
bspc rule -a Gimp -d ^3 --follow --floating

## Configuration
bspc config split_ratio            0.64
bspc config border_width           2
bspc config window_gap             12
bspc config borderless_monocle     false
bspc config gapless_monocle        false
bspc config focus_follows_pointer  true
bspc config history_aware_focus    true
bspc config auto_cancel            true

## History
if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
    rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

## Misc Startup
sxhkd &
compton -cfFb -o 0.32 -O 0.03 -I 0.03 -t -11 -l -11 -r 4 -D2
xsetroot -cursor_name left_ptr
unclutter -root -jitter 5 -idle 2 -noevents &

## Colorscheme - "theme"
source ~/.config/bspwm/colors-fall

## Lastly, start panel.
panel &
