#!/bin/sh

##
# [ ~/.config/bspwm/bspwmrc ]
# Run when bspwm is started.
##

## Monitors, Desktops & Tags
bspc monitor -d 1 2 3

## Window rules
bspc rule -a Gimp -d ^3 --follow --floating

## Configuration
bspc config split_ratio            0.64
bspc config border_width           2
bspc config window_gap             12
bspc config borderless_monocle     false
bspc config gapless_monocle        false
bspc config focus_follows_pointer  true
bspc config history_aware_focus    true
bspc config auto_cancel            true

## Frames
bspc rule -a BSPWM_FRAME --frame
bspc config normal_frame_opacity    0.0
bspc config active_frame_opacity    0.0
bspc config focused_frame_opacity   0.1

## Colorscheme - "theme"
source ~/.config/bspwm/colors/fall

## History
if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
    rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

## Misc Startup
sxhkd &
xsetroot -cursor_name left_ptr
unclutter -root -jitter 5 -idle 2 -noevents &
compton -cfFb -o 0.32 -O 0.03 -I 0.03 -t -11 -l -11 -r 4 -D2 \
    --shadow-exclude 'g:ai:dmenu'

## Lastly, start panel.
panel &
